### ISSUE TITLE
Is that working when only allow with https?

### ISSUE THREAD

**Issue by bishwajitcse** [valb3r/letsencrypt-helper#19]
If code has redirect http to https. And allow only https protocol is that working on that case?

**Comment by valb3r** [comment]
Sorry, not really clear to me what you are trying to describe.

1. Http to Https redirection should work with the library, because http is required only for LetsEncrypt challenge. 
2. You can customise challenge endpoint (that works on http) to redirect to https port

Can you please add more details on your setup?

**Comment by bishwajitcse** [comment]
Thanks, For your response, I had fixed the issue. But this tools is great help. Thanks
